"""Add Transport Pricings

Revision ID: 00d1621326f7
Revises: 6c7c9928dff7
Create Date: 2026-06-02 21:24:32.862300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d1621326f7'
down_revision: Union[str, Sequence[str], None] = '6c7c9928dff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_transport_options',
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('SHARED', 'SEPARATE_VEHICLE', name='transportoptiontype'), nullable=False),
    sa.Column('capacity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('adult_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('child_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weekend_adult_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weekend_child_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fixed_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weekend_fixed_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_package_transport_options_package_id_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_transport_options'))
    )
    op.create_index(op.f('ix_package_transport_options_deleted_at'), 'package_transport_options', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_package_transport_options_id'), 'package_transport_options', ['id'], unique=False)
    op.create_index(op.f('ix_package_transport_options_package_id'), 'package_transport_options', ['package_id'], unique=False)
    op.execute("ALTER TABLE package_variants ADD COLUMN IF NOT EXISTS weekend_adult_price NUMERIC(10, 2)")
    op.execute("ALTER TABLE package_variants ADD COLUMN IF NOT EXISTS weekend_child_price NUMERIC(10, 2)")
    op.drop_column('package_variants', 'transport_info')
    op.execute("ALTER TABLE packages ADD COLUMN IF NOT EXISTS has_transport BOOLEAN DEFAULT 'false' NOT NULL")
    op.execute("ALTER TABLE packages ADD COLUMN IF NOT EXISTS has_refreshments BOOLEAN DEFAULT 'false' NOT NULL")
    op.execute("ALTER TABLE packages ADD COLUMN IF NOT EXISTS refreshment_adult_price NUMERIC(10, 2)")
    op.execute("ALTER TABLE packages ADD COLUMN IF NOT EXISTS refreshment_child_price NUMERIC(10, 2)")
    op.drop_column('packages', 'transport_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE packages ADD COLUMN IF NOT EXISTS transport_info VARCHAR")
    op.drop_column('packages', 'refreshment_child_price')
    op.drop_column('packages', 'refreshment_adult_price')
    op.drop_column('packages', 'has_refreshments')
    op.drop_column('packages', 'has_transport')
    op.execute("ALTER TABLE package_variants ADD COLUMN IF NOT EXISTS transport_info VARCHAR")
    op.drop_column('package_variants', 'weekend_child_price')
    op.drop_column('package_variants', 'weekend_adult_price')
    op.drop_index(op.f('ix_package_transport_options_package_id'), table_name='package_transport_options')
    op.drop_index(op.f('ix_package_transport_options_id'), table_name='package_transport_options')
    op.drop_index(op.f('ix_package_transport_options_deleted_at'), table_name='package_transport_options')
    op.drop_table('package_transport_options')
    # ### end Alembic commands ###
