"""add_gin_index_and_backfill_seo

Revision ID: 03d351e145f8
Revises: f3fa50b6060b
Create Date: 2026-05-16 16:01:21.719135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d351e145f8'
down_revision: Union[str, Sequence[str], None] = 'f3fa50b6060b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_rooms_facilities_gin', 'rooms', ['facilities'], unique=False, postgresql_using='gin')
    
    # Backfill SEO fields for packages
    op.execute("UPDATE packages SET meta_title = title WHERE meta_title IS NULL")
    op.execute("UPDATE packages SET meta_description = LEFT(description, 160) WHERE meta_description IS NULL AND description IS NOT NULL")
    
    # Backfill SEO fields for rooms
    op.execute("UPDATE rooms SET meta_title = lodge_name WHERE meta_title IS NULL")
    op.execute("UPDATE rooms SET meta_description = LEFT(description, 160) WHERE meta_description IS NULL AND description IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rooms_facilities_gin', table_name='rooms', postgresql_using='gin')
    # ### end Alembic commands ###
