"""refactor_booking_transaction_contracts

Revision ID: 0460d2bd65c7
Revises: c9a1e2d3f4b5
Create Date: 2026-05-17 11:57:05.618456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0460d2bd65c7'
down_revision: Union[str, Sequence[str], None] = 'c9a1e2d3f4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_passengers', sa.Column('aadhar_encrypted', sa.String(length=512), nullable=False))
    op.add_column('booking_passengers', sa.Column('aadhar_hash', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_booking_passengers_aadhar_hash'), 'booking_passengers', ['aadhar_hash'], unique=False)
    op.drop_column('booking_passengers', 'aadhar_number')
    op.add_column('bookings', sa.Column('travel_date', sa.Date(), nullable=False))
    op.add_column('bookings', sa.Column('adult_count', sa.Integer(), server_default='1', nullable=False))
    op.add_column('bookings', sa.Column('child_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('bookings', sa.Column('has_refreshment_addon', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('bookings', sa.Column('subtotal_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('bookings', sa.Column('coupon_discount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False))
    op.add_column('bookings', sa.Column('coupon_applied', sa.String(length=50), nullable=True))
    op.add_column('bookings', sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('bookings', sa.Column('gateway_fee', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('bookings', sa.Column('remaining_balance', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('bookings', sa.Column('agent_commission', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False))
    op.alter_column('bookings', 'pricing_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_bookings_travel_date'), 'bookings', ['travel_date'], unique=False)
    op.drop_constraint(op.f('fk_bookings_user_id_users'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_variant_id_package_variants'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_room_variant_id_room_variants'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_agent_id_users'), 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bookings_room_variant_id_room_variants'), 'bookings', 'room_variants', ['room_variant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_bookings_agent_id_users'), 'bookings', 'users', ['agent_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_bookings_user_id_users'), 'bookings', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_bookings_variant_id_package_variants'), 'bookings', 'package_variants', ['variant_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('bookings', 'remaining_amount')
    op.add_column('payments', sa.Column('razorpay_signature', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('error_code', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('error_description', sa.String(), nullable=True))
    op.alter_column('payments', 'razorpay_order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'razorpay_order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('payments', 'error_description')
    op.drop_column('payments', 'error_code')
    op.drop_column('payments', 'razorpay_signature')
    op.add_column('bookings', sa.Column('remaining_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_bookings_variant_id_package_variants'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_user_id_users'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_agent_id_users'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_room_variant_id_room_variants'), 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bookings_agent_id_users'), 'bookings', 'users', ['agent_id'], ['id'])
    op.create_foreign_key(op.f('fk_bookings_room_variant_id_room_variants'), 'bookings', 'room_variants', ['room_variant_id'], ['id'])
    op.create_foreign_key(op.f('fk_bookings_variant_id_package_variants'), 'bookings', 'package_variants', ['variant_id'], ['id'])
    op.create_foreign_key(op.f('fk_bookings_user_id_users'), 'bookings', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_bookings_travel_date'), table_name='bookings')
    op.alter_column('bookings', 'pricing_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('bookings', 'agent_commission')
    op.drop_column('bookings', 'remaining_balance')
    op.drop_column('bookings', 'gateway_fee')
    op.drop_column('bookings', 'gst_amount')
    op.drop_column('bookings', 'coupon_applied')
    op.drop_column('bookings', 'coupon_discount')
    op.drop_column('bookings', 'subtotal_amount')
    op.drop_column('bookings', 'has_refreshment_addon')
    op.drop_column('bookings', 'child_count')
    op.drop_column('bookings', 'adult_count')
    op.drop_column('bookings', 'travel_date')
    op.add_column('booking_passengers', sa.Column('aadhar_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_booking_passengers_aadhar_hash'), table_name='booking_passengers')
    op.drop_column('booking_passengers', 'aadhar_hash')
    op.drop_column('booking_passengers', 'aadhar_encrypted')
    # ### end Alembic commands ###
