"""refactor_booking_transaction_contracts

Revision ID: 0460d2bd65c7
Revises: c9a1e2d3f4b5
Create Date: 2026-05-17 11:57:05.618456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0460d2bd65c7'
down_revision: Union[str, Sequence[str], None] = 'c9a1e2d3f4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE booking_passengers ADD COLUMN IF NOT EXISTS aadhar_encrypted VARCHAR(length=512)")
    op.execute("ALTER TABLE booking_passengers ADD COLUMN IF NOT EXISTS aadhar_hash VARCHAR(length=64)")
    op.create_index(op.f('ix_booking_passengers_aadhar_hash'), 'booking_passengers', ['aadhar_hash'], unique=False)
    op.drop_column('booking_passengers', 'aadhar_number')
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS travel_date TEXT")
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS adult_count INTEGER DEFAULT 1 NOT NULL")
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS child_count INTEGER DEFAULT 0 NOT NULL")
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS has_refreshment_addon BOOLEAN DEFAULT 'false' NOT NULL")
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS subtotal_amount NUMERIC")
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS coupon_discount NUMERIC")
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS coupon_applied VARCHAR(length=50)")
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS gst_amount NUMERIC")
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS gateway_fee NUMERIC")
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS remaining_balance NUMERIC")
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS agent_commission NUMERIC")
    op.alter_column('bookings', 'pricing_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_bookings_travel_date'), 'bookings', ['travel_date'], unique=False)
    op.drop_constraint(op.f('fk_bookings_user_id_users'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_variant_id_package_variants'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_room_variant_id_room_variants'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_agent_id_users'), 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bookings_room_variant_id_room_variants'), 'bookings', 'room_variants', ['room_variant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_bookings_agent_id_users'), 'bookings', 'users', ['agent_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_bookings_user_id_users'), 'bookings', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_bookings_variant_id_package_variants'), 'bookings', 'package_variants', ['variant_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('bookings', 'remaining_amount')
    op.execute("ALTER TABLE payments ADD COLUMN IF NOT EXISTS razorpay_signature VARCHAR(length=255)")
    op.execute("ALTER TABLE payments ADD COLUMN IF NOT EXISTS error_code VARCHAR(length=100)")
    op.execute("ALTER TABLE payments ADD COLUMN IF NOT EXISTS error_description VARCHAR")
    op.alter_column('payments', 'razorpay_order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'razorpay_order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('payments', 'error_description')
    op.drop_column('payments', 'error_code')
    op.drop_column('payments', 'razorpay_signature')
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS remaining_amount TEXT")
    op.drop_constraint(op.f('fk_bookings_variant_id_package_variants'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_user_id_users'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_agent_id_users'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_room_variant_id_room_variants'), 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bookings_agent_id_users'), 'bookings', 'users', ['agent_id'], ['id'])
    op.create_foreign_key(op.f('fk_bookings_room_variant_id_room_variants'), 'bookings', 'room_variants', ['room_variant_id'], ['id'])
    op.create_foreign_key(op.f('fk_bookings_variant_id_package_variants'), 'bookings', 'package_variants', ['variant_id'], ['id'])
    op.create_foreign_key(op.f('fk_bookings_user_id_users'), 'bookings', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_bookings_travel_date'), table_name='bookings')
    op.alter_column('bookings', 'pricing_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('bookings', 'agent_commission')
    op.drop_column('bookings', 'remaining_balance')
    op.drop_column('bookings', 'gateway_fee')
    op.drop_column('bookings', 'gst_amount')
    op.drop_column('bookings', 'coupon_applied')
    op.drop_column('bookings', 'coupon_discount')
    op.drop_column('bookings', 'subtotal_amount')
    op.drop_column('bookings', 'has_refreshment_addon')
    op.drop_column('bookings', 'child_count')
    op.drop_column('bookings', 'adult_count')
    op.drop_column('bookings', 'travel_date')
    op.execute("ALTER TABLE booking_passengers ADD COLUMN IF NOT EXISTS aadhar_number VARCHAR")
    op.drop_index(op.f('ix_booking_passengers_aadhar_hash'), table_name='booking_passengers')
    op.drop_column('booking_passengers', 'aadhar_hash')
    op.drop_column('booking_passengers', 'aadhar_encrypted')
    # ### end Alembic commands ###
