"""Add starting_price to packages and rooms

Revision ID: 1493957fc469
Revises: 627f59f177ae
Create Date: 2026-05-27 22:06:10.780515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1493957fc469'
down_revision: Union[str, Sequence[str], None] = '627f59f177ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('starting_price', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False))
    op.create_index(op.f('ix_packages_starting_price'), 'packages', ['starting_price'], unique=False)
    op.add_column('rooms', sa.Column('starting_price', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False))
    op.create_index(op.f('ix_rooms_starting_price'), 'rooms', ['starting_price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_starting_price'), table_name='rooms')
    op.drop_column('rooms', 'starting_price')
    op.drop_index(op.f('ix_packages_starting_price'), table_name='packages')
    op.drop_column('packages', 'starting_price')
    # ### end Alembic commands ###
