"""add_booking_drafts_and_reserved_capacity

Revision ID: 177b113cbd3f
Revises: 32792b213b0e
Create Date: 2026-05-20 19:10:12.100911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '177b113cbd3f'
down_revision: Union[str, Sequence[str], None] = '32792b213b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_drafts',
    sa.Column('draft_id', sa.String(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('checkout_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pricing_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('room_variant_id', sa.Integer(), nullable=True),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount_payable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('coupon_applied', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('fk_booking_drafts_agent_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_booking_drafts_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_drafts'))
    )
    op.create_index(op.f('ix_booking_drafts_agent_id'), 'booking_drafts', ['agent_id'], unique=False)
    op.create_index(op.f('ix_booking_drafts_deleted_at'), 'booking_drafts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_booking_drafts_draft_id'), 'booking_drafts', ['draft_id'], unique=True)
    op.create_index(op.f('ix_booking_drafts_expires_at'), 'booking_drafts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_booking_drafts_id'), 'booking_drafts', ['id'], unique=False)
    op.create_index(op.f('ix_booking_drafts_razorpay_order_id'), 'booking_drafts', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_booking_drafts_user_id'), 'booking_drafts', ['user_id'], unique=False)
    op.add_column('package_variant_inventory', sa.Column('reserved_count', sa.Integer(), server_default='0', nullable=False))
    op.drop_index(op.f('ix_packages_fts'), table_name='packages', postgresql_using='gin')
    op.create_index('ix_packages_fts', 'packages', [sa.literal_column("to_tsvector('english'::regconfig, title || ' ' || coalesce(description, ''))")], unique=False, postgresql_using='gin')
    op.add_column('room_slot_inventory', sa.Column('reserved_rooms', sa.Integer(), server_default='0', nullable=False))
    op.drop_constraint(op.f('uq_room_slot_inventory'), 'room_slot_inventory', type_='unique')
    op.drop_index(op.f('ix_rooms_active_priority'), table_name='rooms', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_rooms_fts'), table_name='rooms', postgresql_using='gin')
    op.add_column('users', sa.Column('white_label_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'white_label_enabled')
    op.create_index(op.f('ix_rooms_fts'), 'rooms', [sa.literal_column("to_tsvector('english'::regconfig, (((lodge_name::text || ' '::text) || COALESCE(address, ''::character varying)::text) || ' '::text) || COALESCE(description, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_rooms_active_priority'), 'rooms', ['is_active', 'order_priority'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_constraint('uq_room_slot_inventory_variant', 'room_slot_inventory', type_='unique')
    op.create_unique_constraint(op.f('uq_room_slot_inventory'), 'room_slot_inventory', ['room_variant_id', 'date', 'slot_start', 'slot_end'], postgresql_nulls_not_distinct=False)
    op.drop_column('room_slot_inventory', 'reserved_rooms')
    op.drop_index('ix_packages_fts', table_name='packages', postgresql_using='gin')
    op.create_index(op.f('ix_packages_fts'), 'packages', [sa.literal_column("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.drop_column('package_variant_inventory', 'reserved_count')
    op.drop_index(op.f('ix_booking_drafts_user_id'), table_name='booking_drafts')
    op.drop_index(op.f('ix_booking_drafts_razorpay_order_id'), table_name='booking_drafts')
    op.drop_index(op.f('ix_booking_drafts_id'), table_name='booking_drafts')
    op.drop_index(op.f('ix_booking_drafts_expires_at'), table_name='booking_drafts')
    op.drop_index(op.f('ix_booking_drafts_draft_id'), table_name='booking_drafts')
    op.drop_index(op.f('ix_booking_drafts_deleted_at'), table_name='booking_drafts')
    op.drop_index(op.f('ix_booking_drafts_agent_id'), table_name='booking_drafts')
    op.drop_table('booking_drafts')
    # ### end Alembic commands ###
