"""add_room_indexes

Revision ID: 1d5153b6ef92
Revises: 5ec6f3888fa0
Create Date: 2026-05-17 22:53:30.557198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5153b6ef92'
down_revision: Union[str, Sequence[str], None] = '5ec6f3888fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_rooms_is_active'), 'rooms', ['is_active'], unique=False)
    op.create_index(op.f('ix_rooms_is_featured'), 'rooms', ['is_featured'], unique=False)
    op.create_index(op.f('ix_rooms_order_priority'), 'rooms', ['order_priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_order_priority'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_is_featured'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_is_active'), table_name='rooms')
    # ### end Alembic commands ###
