"""Ultimate Hardened Phase 1 schema

Revision ID: 2fd6c4179c90
Revises: 
Create Date: 2026-05-16 01:52:04.400323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fd6c4179c90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_ons',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price_per_person', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_add_ons'))
    )
    op.create_index(op.f('ix_add_ons_deleted_at'), 'add_ons', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_add_ons_id'), 'add_ons', ['id'], unique=False)
    op.create_table('packages',
    sa.Column('type', sa.Enum('TOUR', 'TRIP', name='packagetype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('region', sa.Enum('AP', 'TS', name='regiontype'), nullable=True),
    sa.Column('order_priority', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packages'))
    )
    op.create_index(op.f('ix_packages_deleted_at'), 'packages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_packages_id'), 'packages', ['id'], unique=False)
    op.create_index(op.f('ix_packages_is_active'), 'packages', ['is_active'], unique=False)
    op.create_index(op.f('ix_packages_slug'), 'packages', ['slug'], unique=True)
    op.create_table('rooms',
    sa.Column('lodge_name', sa.String(), nullable=False),
    sa.Column('room_type', sa.String(), nullable=False),
    sa.Column('weekday_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('weekend_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('slot_start', sa.Time(), nullable=False),
    sa.Column('slot_end', sa.Time(), nullable=False),
    sa.Column('total_rooms', sa.Integer(), nullable=False),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('order_priority', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms'))
    )
    op.create_index(op.f('ix_rooms_deleted_at'), 'rooms', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_is_active'), 'rooms', ['is_active'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_deleted_at'), 'tags', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('role', sa.Enum('ADMIN', 'AGENT', 'USER', name='userrole'), server_default='USER', nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('account_status', sa.Enum('ACTIVE', 'BLOCKED', 'DISABLED', name='accountstatus'), server_default='ACTIVE', nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('package_tags',
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_package_tags_package_id_packages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_package_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('package_id', 'tag_id', name=op.f('pk_package_tags'))
    )
    op.create_table('package_variants',
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('adult_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('child_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transport_info', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_package_variants_package_id_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_variants'))
    )
    op.create_index(op.f('ix_package_variants_deleted_at'), 'package_variants', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_package_variants_id'), 'package_variants', ['id'], unique=False)
    op.create_index(op.f('ix_package_variants_is_active'), 'package_variants', ['is_active'], unique=False)
    op.create_index(op.f('ix_package_variants_package_id'), 'package_variants', ['package_id'], unique=False)
    op.create_table('room_slot_inventory',
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slot_start', sa.Time(), nullable=False),
    sa.Column('slot_end', sa.Time(), nullable=False),
    sa.Column('total_rooms', sa.Integer(), nullable=False),
    sa.Column('booked_rooms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_rooms', sa.Integer(), sa.Computed('total_rooms - booked_rooms', persisted=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('booked_rooms <= total_rooms', name=op.f('ck_room_slot_inventory_chk_room_capacity')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_slot_inventory_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_slot_inventory')),
    sa.UniqueConstraint('room_id', 'date', 'slot_start', 'slot_end', name='uq_room_slot_inventory')
    )
    op.create_index(op.f('ix_room_slot_inventory_date'), 'room_slot_inventory', ['date'], unique=False)
    op.create_index(op.f('ix_room_slot_inventory_deleted_at'), 'room_slot_inventory', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_room_slot_inventory_id'), 'room_slot_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_room_slot_inventory_room_id'), 'room_slot_inventory', ['room_id'], unique=False)
    op.create_table('bookings',
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.Enum('ADMIN', 'USER', 'AGENT', name='bookingsource'), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('variant_id', sa.BigInteger(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL_PAID', 'FULLY_PAID', 'CANCELLED', 'REFUNDED', name='bookingstatus'), server_default='PENDING', nullable=False),
    sa.Column('pricing_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(room_id IS NOT NULL AND variant_id IS NULL) OR (room_id IS NULL AND variant_id IS NOT NULL)', name=op.f('ck_bookings_chk_booking_target')),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('fk_bookings_agent_id_users')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_bookings_room_id_rooms')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookings_user_id_users')),
    sa.ForeignKeyConstraint(['variant_id'], ['package_variants.id'], name=op.f('fk_bookings_variant_id_package_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_index(op.f('ix_bookings_agent_id'), 'bookings', ['agent_id'], unique=False)
    op.create_index('ix_bookings_created_at', 'bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookings_deleted_at'), 'bookings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_public_id'), 'bookings', ['public_id'], unique=True)
    op.create_index(op.f('ix_bookings_room_id'), 'bookings', ['room_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_index(op.f('ix_bookings_variant_id'), 'bookings', ['variant_id'], unique=False)
    op.create_table('package_variant_inventory',
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('booked_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('booked_count <= total_capacity', name=op.f('ck_package_variant_inventory_chk_variant_capacity')),
    sa.ForeignKeyConstraint(['variant_id'], ['package_variants.id'], name=op.f('fk_package_variant_inventory_variant_id_package_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_variant_inventory')),
    sa.UniqueConstraint('variant_id', 'date', name='uq_variant_inventory')
    )
    op.create_index(op.f('ix_package_variant_inventory_date'), 'package_variant_inventory', ['date'], unique=False)
    op.create_index(op.f('ix_package_variant_inventory_deleted_at'), 'package_variant_inventory', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_package_variant_inventory_id'), 'package_variant_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_package_variant_inventory_variant_id'), 'package_variant_inventory', ['variant_id'], unique=False)
    op.create_table('booking_passengers',
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gendertype'), nullable=True),
    sa.Column('is_child', sa.Boolean(), sa.Computed('age < 10', persisted=True), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('aadhar_number', sa.String(), nullable=False),
    sa.Column('aadhar_image_url', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_passengers_booking_id_bookings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_passengers'))
    )
    op.create_index(op.f('ix_booking_passengers_booking_id'), 'booking_passengers', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_passengers_deleted_at'), 'booking_passengers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_booking_passengers_id'), 'booking_passengers', ['id'], unique=False)
    op.create_table('booking_stay_dates',
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_stay_dates_booking_id_bookings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_stay_dates')),
    sa.UniqueConstraint('booking_id', 'date', name='uq_booking_stay_date')
    )
    op.create_index(op.f('ix_booking_stay_dates_booking_id'), 'booking_stay_dates', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_stay_dates_date'), 'booking_stay_dates', ['date'], unique=False)
    op.create_index(op.f('ix_booking_stay_dates_deleted_at'), 'booking_stay_dates', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_booking_stay_dates_id'), 'booking_stay_dates', ['id'], unique=False)
    op.create_table('cancellation_requests',
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REFUNDED', name='cancellationstatus'), server_default='PENDING', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_by', sa.BigInteger(), nullable=True),
    sa.Column('admin_notes', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_cancellation_requests_booking_id_bookings')),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], name=op.f('fk_cancellation_requests_processed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cancellation_requests'))
    )
    op.create_index(op.f('ix_cancellation_requests_booking_id'), 'cancellation_requests', ['booking_id'], unique=False)
    op.create_index(op.f('ix_cancellation_requests_deleted_at'), 'cancellation_requests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_cancellation_requests_id'), 'cancellation_requests', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'CAPTURED', 'FAILED', 'REFUNDED', name='paymentstatus'), server_default='CREATED', nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payments_booking_id_bookings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_deleted_at'), 'payments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_deleted_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_cancellation_requests_id'), table_name='cancellation_requests')
    op.drop_index(op.f('ix_cancellation_requests_deleted_at'), table_name='cancellation_requests')
    op.drop_index(op.f('ix_cancellation_requests_booking_id'), table_name='cancellation_requests')
    op.drop_table('cancellation_requests')
    op.drop_index(op.f('ix_booking_stay_dates_id'), table_name='booking_stay_dates')
    op.drop_index(op.f('ix_booking_stay_dates_deleted_at'), table_name='booking_stay_dates')
    op.drop_index(op.f('ix_booking_stay_dates_date'), table_name='booking_stay_dates')
    op.drop_index(op.f('ix_booking_stay_dates_booking_id'), table_name='booking_stay_dates')
    op.drop_table('booking_stay_dates')
    op.drop_index(op.f('ix_booking_passengers_id'), table_name='booking_passengers')
    op.drop_index(op.f('ix_booking_passengers_deleted_at'), table_name='booking_passengers')
    op.drop_index(op.f('ix_booking_passengers_booking_id'), table_name='booking_passengers')
    op.drop_table('booking_passengers')
    op.drop_index(op.f('ix_package_variant_inventory_variant_id'), table_name='package_variant_inventory')
    op.drop_index(op.f('ix_package_variant_inventory_id'), table_name='package_variant_inventory')
    op.drop_index(op.f('ix_package_variant_inventory_deleted_at'), table_name='package_variant_inventory')
    op.drop_index(op.f('ix_package_variant_inventory_date'), table_name='package_variant_inventory')
    op.drop_table('package_variant_inventory')
    op.drop_index(op.f('ix_bookings_variant_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_room_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_public_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_deleted_at'), table_name='bookings')
    op.drop_index('ix_bookings_created_at', table_name='bookings')
    op.drop_index(op.f('ix_bookings_agent_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_room_slot_inventory_room_id'), table_name='room_slot_inventory')
    op.drop_index(op.f('ix_room_slot_inventory_id'), table_name='room_slot_inventory')
    op.drop_index(op.f('ix_room_slot_inventory_deleted_at'), table_name='room_slot_inventory')
    op.drop_index(op.f('ix_room_slot_inventory_date'), table_name='room_slot_inventory')
    op.drop_table('room_slot_inventory')
    op.drop_index(op.f('ix_package_variants_package_id'), table_name='package_variants')
    op.drop_index(op.f('ix_package_variants_is_active'), table_name='package_variants')
    op.drop_index(op.f('ix_package_variants_id'), table_name='package_variants')
    op.drop_index(op.f('ix_package_variants_deleted_at'), table_name='package_variants')
    op.drop_table('package_variants')
    op.drop_table('package_tags')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_deleted_at'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_rooms_is_active'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_deleted_at'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_packages_slug'), table_name='packages')
    op.drop_index(op.f('ix_packages_is_active'), table_name='packages')
    op.drop_index(op.f('ix_packages_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_deleted_at'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_add_ons_id'), table_name='add_ons')
    op.drop_index(op.f('ix_add_ons_deleted_at'), table_name='add_ons')
    op.drop_table('add_ons')
    # ### end Alembic commands ###
