"""add_is_closed_to_room_slot_inventory

Revision ID: 32792b213b0e
Revises: e1a2b3c4d5f6
Create Date: 2026-05-20 16:07:18.115830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32792b213b0e'
down_revision: Union[str, Sequence[str], None] = 'e1a2b3c4d5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_inventory_variant_date'), table_name='package_variant_inventory')
    op.drop_index(op.f('ix_packages_fts'), table_name='packages', postgresql_using='gin')
    op.create_index('ix_packages_fts', 'packages', [sa.literal_column("to_tsvector('english'::regconfig, title || ' ' || coalesce(description, ''))")], unique=False, postgresql_using='gin')
    op.add_column('room_slot_inventory', sa.Column('is_closed', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index(op.f('ix_room_slot_inventory_room_date'), table_name='room_slot_inventory')
    op.drop_index(op.f('ix_rooms_fts'), table_name='rooms', postgresql_using='gin')
    op.create_index('ix_rooms_fts', 'rooms', [sa.literal_column("to_tsvector('english'::regconfig, lodge_name || ' ' || coalesce(address, '') || ' ' || coalesce(description, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rooms_fts', table_name='rooms', postgresql_using='gin')
    op.create_index(op.f('ix_rooms_fts'), 'rooms', [sa.literal_column("to_tsvector('english'::regconfig, (((lodge_name::text || ' '::text) || COALESCE(address, ''::character varying)::text) || ' '::text) || COALESCE(description, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_room_slot_inventory_room_date'), 'room_slot_inventory', ['room_id', 'date'], unique=False)
    op.drop_column('room_slot_inventory', 'is_closed')
    op.drop_index('ix_packages_fts', table_name='packages', postgresql_using='gin')
    op.create_index(op.f('ix_packages_fts'), 'packages', [sa.literal_column("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_package_inventory_variant_date'), 'package_variant_inventory', ['variant_id', 'date'], unique=False)
    # ### end Alembic commands ###
