"""add min_tickets to coupons

Revision ID: 4d65e48275c7
Revises: 24da6073143d
Create Date: 2026-05-27 13:08:06.219589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d65e48275c7'
down_revision: Union[str, Sequence[str], None] = '24da6073143d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('min_tickets', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'min_tickets')
    # ### end Alembic commands ###
