"""add_brochure_pdf_url_to_packages

Revision ID: 54c59b329caf
Revises: 0460d2bd65c7
Create Date: 2026-05-17 12:13:32.080500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c59b329caf'
down_revision: Union[str, Sequence[str], None] = '0460d2bd65c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE packages ADD COLUMN IF NOT EXISTS brochure_pdf_url VARCHAR")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'brochure_pdf_url')
    # ### end Alembic commands ###
