"""Add document generation fields

Revision ID: 6069a223584e
Revises: 1d5153b6ef92
Create Date: 2026-05-18 01:54:25.507708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6069a223584e'
down_revision: Union[str, Sequence[str], None] = '1d5153b6ef92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    """Upgrade schema."""
    # Create the ENUM type explicitly for PostgreSQL
    document_generation_status = postgresql.ENUM('AVAILABLE', 'GENERATING', 'FAILED', 'MISSING', name='documentgenerationstatus')
    document_generation_status.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS ticket_pdf_url VARCHAR")
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS invoice_pdf_url VARCHAR")
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS ticket_generation_status TEXT")
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS invoice_generation_status TEXT")
    op.execute("ALTER TABLE packages ADD COLUMN IF NOT EXISTS brochure_generation_status TEXT")
    op.execute("ALTER TABLE rooms ADD COLUMN IF NOT EXISTS brochure_pdf_url VARCHAR")
    op.execute("ALTER TABLE rooms ADD COLUMN IF NOT EXISTS generated_brochure_url VARCHAR")
    op.execute("ALTER TABLE rooms ADD COLUMN IF NOT EXISTS brochure_generation_status TEXT")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'brochure_generation_status')
    op.drop_column('rooms', 'generated_brochure_url')
    op.drop_column('rooms', 'brochure_pdf_url')
    op.drop_column('packages', 'brochure_generation_status')
    op.drop_column('bookings', 'invoice_generation_status')
    op.drop_column('bookings', 'ticket_generation_status')
    op.drop_column('bookings', 'invoice_pdf_url')
    op.drop_column('bookings', 'ticket_pdf_url')
    # ### end Alembic commands ###
    
    # Drop the ENUM type explicitly for PostgreSQL
    document_generation_status = postgresql.ENUM('AVAILABLE', 'GENERATING', 'FAILED', 'MISSING', name='documentgenerationstatus')
    document_generation_status.drop(op.get_bind(), checkfirst=True)
