"""Add document generation fields

Revision ID: 6069a223584e
Revises: 1d5153b6ef92
Create Date: 2026-05-18 01:54:25.507708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6069a223584e'
down_revision: Union[str, Sequence[str], None] = '1d5153b6ef92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    """Upgrade schema."""
    # Create the ENUM type explicitly for PostgreSQL
    document_generation_status = postgresql.ENUM('AVAILABLE', 'GENERATING', 'FAILED', 'MISSING', name='documentgenerationstatus')
    document_generation_status.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('ticket_pdf_url', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('invoice_pdf_url', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('ticket_generation_status', sa.Enum('AVAILABLE', 'GENERATING', 'FAILED', 'MISSING', name='documentgenerationstatus'), server_default='MISSING', nullable=False))
    op.add_column('bookings', sa.Column('invoice_generation_status', sa.Enum('AVAILABLE', 'GENERATING', 'FAILED', 'MISSING', name='documentgenerationstatus'), server_default='MISSING', nullable=False))
    op.add_column('packages', sa.Column('brochure_generation_status', sa.Enum('AVAILABLE', 'GENERATING', 'FAILED', 'MISSING', name='documentgenerationstatus'), server_default='MISSING', nullable=False))
    op.add_column('rooms', sa.Column('brochure_pdf_url', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('generated_brochure_url', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('brochure_generation_status', sa.Enum('AVAILABLE', 'GENERATING', 'FAILED', 'MISSING', name='documentgenerationstatus'), server_default='MISSING', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'brochure_generation_status')
    op.drop_column('rooms', 'generated_brochure_url')
    op.drop_column('rooms', 'brochure_pdf_url')
    op.drop_column('packages', 'brochure_generation_status')
    op.drop_column('bookings', 'invoice_generation_status')
    op.drop_column('bookings', 'ticket_generation_status')
    op.drop_column('bookings', 'invoice_pdf_url')
    op.drop_column('bookings', 'ticket_pdf_url')
    # ### end Alembic commands ###
    
    # Drop the ENUM type explicitly for PostgreSQL
    document_generation_status = postgresql.ENUM('AVAILABLE', 'GENERATING', 'FAILED', 'MISSING', name='documentgenerationstatus')
    document_generation_status.drop(op.get_bind(), checkfirst=True)
