"""add_payment_ledger_audit_columns

Revision ID: 627f59f177ae
Revises: 4d65e48275c7
Create Date: 2026-05-27 15:56:08.786423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627f59f177ae'
down_revision: Union[str, Sequence[str], None] = '4d65e48275c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add nullable first so existing rows don't violate NOT NULL immediately
    op.add_column('payments', sa.Column('payment_reference_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('collected_by_type', sa.String(length=50), server_default='RAZORPAY', nullable=False))
    op.add_column('payments', sa.Column('collected_by_user_id', sa.BigInteger(), nullable=True))
    op.add_column('payments', sa.Column('collected_by_label', sa.String(length=255), nullable=True))

    # 2. Backfill: existing rows all have razorpay_order_id — use that as reference
    op.execute("""
        UPDATE payments
        SET payment_reference_id = COALESCE(razorpay_order_id, 'BACKFILL_' || id::text)
        WHERE payment_reference_id IS NULL
    """)

    # 3. Backfill payment_method for any existing NULL rows
    op.execute("UPDATE payments SET payment_method = 'RAZORPAY' WHERE payment_method IS NULL")

    # 4. Now apply NOT NULL + unique constraints
    op.alter_column('payments', 'payment_reference_id', nullable=False)
    op.alter_column('payments', 'payment_method', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('payments', 'razorpay_order_id', existing_type=sa.VARCHAR(), nullable=True)

    op.create_index(op.f('ix_payments_payment_reference_id'), 'payments', ['payment_reference_id'], unique=True)
    op.create_foreign_key(op.f('fk_payments_collected_by_user_id_users'), 'payments', 'users', ['collected_by_user_id'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_payments_collected_by_user_id_users'), 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_payment_reference_id'), table_name='payments')
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'razorpay_order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('payments', 'collected_by_label')
    op.drop_column('payments', 'collected_by_user_id')
    op.drop_column('payments', 'collected_by_type')
    op.drop_column('payments', 'payment_reference_id')
    # ### end Alembic commands ###
