"""Add starting_weekend_price to Room

Revision ID: 6c7c9928dff7
Revises: 89d7d812f064
Create Date: 2026-05-27 22:36:48.861717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7c9928dff7'
down_revision: Union[str, Sequence[str], None] = '89d7d812f064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('starting_weekend_price', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'starting_weekend_price')
    # ### end Alembic commands ###
