"""Refactor Room Architecture to Normalized Lodges

Revision ID: 80a25e03dce8
Revises: 2fd6c4179c90
Create Date: 2026-05-16 11:19:40.069013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80a25e03dce8'
down_revision: Union[str, Sequence[str], None] = '2fd6c4179c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_variants',
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('variant_name', sa.String(), nullable=False),
    sa.Column('weekday_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('weekend_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capacity_per_room', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_variants_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_variants')),
    sa.UniqueConstraint('room_id', 'variant_name', name='uq_room_variant')
    )
    op.create_index(op.f('ix_room_variants_deleted_at'), 'room_variants', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_room_variants_id'), 'room_variants', ['id'], unique=False)
    op.create_index(op.f('ix_room_variants_is_active'), 'room_variants', ['is_active'], unique=False)
    op.create_index(op.f('ix_room_variants_room_id'), 'room_variants', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_variants_variant_name'), 'room_variants', ['variant_name'], unique=False)
    op.create_index(op.f('ix_room_variants_weekday_price'), 'room_variants', ['weekday_price'], unique=False)
    op.create_index(op.f('ix_room_variants_weekend_price'), 'room_variants', ['weekend_price'], unique=False)
    op.add_column('bookings', sa.Column('room_variant_id', sa.BigInteger(), nullable=True))
    op.drop_index(op.f('ix_bookings_room_id'), table_name='bookings')
    op.create_index(op.f('ix_bookings_room_variant_id'), 'bookings', ['room_variant_id'], unique=False)
    op.drop_constraint(op.f('fk_bookings_room_id_rooms'), 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bookings_room_variant_id_room_variants'), 'bookings', 'room_variants', ['room_variant_id'], ['id'])
    op.drop_column('bookings', 'room_id')
    op.add_column('rooms', sa.Column('address', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('facilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('rooms', sa.Column('booked_rooms', sa.Integer(), server_default='0', nullable=False))
    op.add_column('rooms', sa.Column('available_rooms', sa.Integer(), sa.Computed('total_rooms - booked_rooms', persisted=True), nullable=True))
    op.alter_column('rooms', 'order_priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_rooms_is_active'), table_name='rooms')
    op.create_index(op.f('ix_rooms_lodge_name'), 'rooms', ['lodge_name'], unique=False)
    op.drop_column('rooms', 'weekday_price')
    op.drop_column('rooms', 'weekend_price')
    op.drop_column('rooms', 'room_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('room_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('rooms', sa.Column('weekend_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('rooms', sa.Column('weekday_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_rooms_lodge_name'), table_name='rooms')
    op.create_index(op.f('ix_rooms_is_active'), 'rooms', ['is_active'], unique=False)
    op.alter_column('rooms', 'order_priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('rooms', 'available_rooms')
    op.drop_column('rooms', 'booked_rooms')
    op.drop_column('rooms', 'facilities')
    op.drop_column('rooms', 'address')
    op.add_column('bookings', sa.Column('room_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_bookings_room_variant_id_room_variants'), 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bookings_room_id_rooms'), 'bookings', 'rooms', ['room_id'], ['id'])
    op.drop_index(op.f('ix_bookings_room_variant_id'), table_name='bookings')
    op.create_index(op.f('ix_bookings_room_id'), 'bookings', ['room_id'], unique=False)
    op.drop_column('bookings', 'room_variant_id')
    op.drop_index(op.f('ix_room_variants_weekend_price'), table_name='room_variants')
    op.drop_index(op.f('ix_room_variants_weekday_price'), table_name='room_variants')
    op.drop_index(op.f('ix_room_variants_variant_name'), table_name='room_variants')
    op.drop_index(op.f('ix_room_variants_room_id'), table_name='room_variants')
    op.drop_index(op.f('ix_room_variants_is_active'), table_name='room_variants')
    op.drop_index(op.f('ix_room_variants_id'), table_name='room_variants')
    op.drop_index(op.f('ix_room_variants_deleted_at'), table_name='room_variants')
    op.drop_table('room_variants')
    # ### end Alembic commands ###
