"""add_publish_status_to_packages_and_rooms

Revision ID: 84e3818feb23
Revises: 1971202c36e0
Create Date: 2026-05-17 09:41:29.192077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e3818feb23'
down_revision: Union[str, Sequence[str], None] = '1971202c36e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create publishstatus enum
    publishstatus = sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='publishstatus')
    publishstatus.create(op.get_bind(), checkfirst=True)

    op.execute("ALTER TABLE packages ADD COLUMN IF NOT EXISTS status TEXT")
    op.create_index(op.f('ix_packages_status'), 'packages', ['status'], unique=False)
    op.execute("ALTER TABLE rooms ADD COLUMN IF NOT EXISTS status TEXT")
    op.create_index(op.f('ix_rooms_status'), 'rooms', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_status'), table_name='rooms')
    op.drop_column('rooms', 'status')
    op.drop_index(op.f('ix_packages_status'), table_name='packages')
    op.drop_column('packages', 'status')

    # Drop publishstatus enum
    publishstatus = sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='publishstatus')
    publishstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
