"""Add transport_info to Package

Revision ID: 89d7d812f064
Revises: 1493957fc469
Create Date: 2026-05-27 22:32:58.610992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d7d812f064'
down_revision: Union[str, Sequence[str], None] = '1493957fc469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('transport_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'transport_info')
    # ### end Alembic commands ###
