"""Add missing cascades

Revision ID: 91455a7d168b
Revises: f9d65f0ca8a6
Create Date: 2026-05-23 16:00:32.024402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91455a7d168b'
down_revision: Union[str, Sequence[str], None] = 'f9d65f0ca8a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_cancellation_requests_booking_id_bookings'), 'cancellation_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cancellation_requests_booking_id_bookings'), 'cancellation_requests', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_packages_fts'), table_name='packages', postgresql_using='gin')
    op.create_index('ix_packages_fts', 'packages', [sa.literal_column("to_tsvector('english'::regconfig, title || ' ' || coalesce(description, ''))")], unique=False, postgresql_using='gin')
    op.drop_constraint(op.f('fk_payments_booking_id_bookings'), 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_payments_booking_id_bookings'), 'payments', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_payments_booking_id_bookings'), 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_payments_booking_id_bookings'), 'payments', 'bookings', ['booking_id'], ['id'])
    op.drop_index('ix_packages_fts', table_name='packages', postgresql_using='gin')
    op.create_index(op.f('ix_packages_fts'), 'packages', [sa.literal_column("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.drop_constraint(op.f('fk_cancellation_requests_booking_id_bookings'), 'cancellation_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cancellation_requests_booking_id_bookings'), 'cancellation_requests', 'bookings', ['booking_id'], ['id'])
    # ### end Alembic commands ###
