"""add_agent_package_quotas

Revision ID: 998a93c97ed2
Revises: 0a55a16d52e9
Create Date: 2026-06-13 18:42:55.169228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998a93c97ed2'
down_revision: Union[str, Sequence[str], None] = '0a55a16d52e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_package_quotas',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('daily_quota', sa.Integer(), server_default='10', nullable=False),
    sa.Column('is_allowed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('fk_agent_package_quotas_agent_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_agent_package_quotas_package_id_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_package_quotas')),
    sa.UniqueConstraint('agent_id', 'package_id', name='uq_agent_package_quota')
    )
    op.create_index(op.f('ix_agent_package_quotas_agent_id'), 'agent_package_quotas', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_package_quotas_deleted_at'), 'agent_package_quotas', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_agent_package_quotas_id'), 'agent_package_quotas', ['id'], unique=False)
    op.create_index(op.f('ix_agent_package_quotas_package_id'), 'agent_package_quotas', ['package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_package_quotas_package_id'), table_name='agent_package_quotas')
    op.drop_index(op.f('ix_agent_package_quotas_id'), table_name='agent_package_quotas')
    op.drop_index(op.f('ix_agent_package_quotas_deleted_at'), table_name='agent_package_quotas')
    op.drop_index(op.f('ix_agent_package_quotas_agent_id'), table_name='agent_package_quotas')
    op.drop_table('agent_package_quotas')
    # ### end Alembic commands ###
