"""Update is_child computed column

Revision ID: c1770dedc362
Revises: 8bb37beee459
Create Date: 2026-05-21 21:02:44.379077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1770dedc362'
down_revision: Union[str, Sequence[str], None] = '8bb37beee459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop old computed column and add new one
    op.drop_column('booking_passengers', 'is_child')
    op.add_column('booking_passengers', sa.Column('is_child', sa.Boolean(), sa.Computed('age <= 10', persisted=True)))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_passengers', 'is_child')
    op.add_column('booking_passengers', sa.Column('is_child', sa.Boolean(), sa.Computed('age < 10', persisted=True)))
    # ### end Alembic commands ###
