"""remove_cashfree_app_id

Revision ID: cf24ad004179
Revises: 3b87ef55f3f6
Create Date: 2026-07-20 23:53:47.183006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf24ad004179'
down_revision: Union[str, Sequence[str], None] = '3b87ef55f3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'cashfree_app_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('cashfree_app_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
