"""remove_cashfree_app_id

Revision ID: cf24ad004179
Revises: 3b87ef55f3f6
Create Date: 2026-07-20 23:53:47.183006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf24ad004179'
down_revision: Union[str, Sequence[str], None] = '3b87ef55f3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TABLE system_settings DROP COLUMN IF EXISTS cashfree_app_id")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS cashfree_app_id VARCHAR")
    # ### end Alembic commands ###
