"""Add FTS and partial indexes

Revision ID: d8873fd7d851
Revises: b7c9d2e4f6a8
Create Date: 2026-05-19 12:34:46.512979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8873fd7d851'
down_revision: Union[str, Sequence[str], None] = 'b7c9d2e4f6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_packages_fts', 'packages', [sa.literal_column("to_tsvector('english'::regconfig, title || ' ' || coalesce(description, ''))")], unique=False, postgresql_using='gin')
    op.create_index('ix_packages_type_region', 'packages', ['type', 'region', 'is_active', 'order_priority'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_rooms_active_priority', 'rooms', ['is_active', 'order_priority'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_rooms_fts', 'rooms', [sa.literal_column("to_tsvector('english'::regconfig, lodge_name || ' ' || coalesce(address, '') || ' ' || coalesce(description, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rooms_fts', table_name='rooms', postgresql_using='gin')
    op.drop_index('ix_rooms_active_priority', table_name='rooms', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_packages_type_region', table_name='packages', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_packages_fts', table_name='packages', postgresql_using='gin')
    # ### end Alembic commands ###
