"""add_cancellation_fee_to_requests

Revision ID: da5425141eff
Revises: 177b113cbd3f
Create Date: 2026-05-21 14:20:54.609500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5425141eff'
down_revision: Union[str, Sequence[str], None] = '177b113cbd3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cancellation_requests', sa.Column('cancellation_fee', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('cancellation_requests', sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.drop_index(op.f('ix_packages_fts'), table_name='packages', postgresql_using='gin')
    op.create_index('ix_packages_fts', 'packages', [sa.literal_column("to_tsvector('english'::regconfig, title || ' ' || coalesce(description, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_packages_fts', table_name='packages', postgresql_using='gin')
    op.create_index(op.f('ix_packages_fts'), 'packages', [sa.literal_column("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.drop_column('cancellation_requests', 'refund_amount')
    op.drop_column('cancellation_requests', 'cancellation_fee')
    # ### end Alembic commands ###
