"""add_pre_bookings_table

Revision ID: e801872e661c
Revises: c1a2b3d4e5f6
Create Date: 2026-09-01 22:26:06.003772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e801872e661c'
down_revision: Union[str, Sequence[str], None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_bookings',
    sa.Column('ref_id', sa.String(length=30), nullable=False),
    sa.Column('package_id', sa.String(length=100), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('adult_count', sa.Integer(), nullable=False),
    sa.Column('child_count', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_contacted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('admin_notes', sa.String(length=1000), nullable=True),
    sa.Column('user_email_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('admin_email_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pre_bookings'))
    )
    op.create_index('ix_pre_bookings_created_at', 'pre_bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_pre_bookings_customer_email'), 'pre_bookings', ['customer_email'], unique=False)
    op.create_index(op.f('ix_pre_bookings_deleted_at'), 'pre_bookings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_pre_bookings_id'), 'pre_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_pre_bookings_package_id'), 'pre_bookings', ['package_id'], unique=False)
    op.create_index(op.f('ix_pre_bookings_ref_id'), 'pre_bookings', ['ref_id'], unique=True)
    op.create_index('ix_pre_bookings_travel_date', 'pre_bookings', ['travel_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pre_bookings_travel_date', table_name='pre_bookings')
    op.drop_index(op.f('ix_pre_bookings_ref_id'), table_name='pre_bookings')
    op.drop_index(op.f('ix_pre_bookings_package_id'), table_name='pre_bookings')
    op.drop_index(op.f('ix_pre_bookings_id'), table_name='pre_bookings')
    op.drop_index(op.f('ix_pre_bookings_deleted_at'), table_name='pre_bookings')
    op.drop_index(op.f('ix_pre_bookings_customer_email'), table_name='pre_bookings')
    op.drop_index('ix_pre_bookings_created_at', table_name='pre_bookings')
    op.drop_table('pre_bookings')
    # ### end Alembic commands ###
