"""add_content_layer

Revision ID: f3fa50b6060b
Revises: 80a25e03dce8
Create Date: 2026-05-16 15:55:25.977646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3fa50b6060b'
down_revision: Union[str, Sequence[str], None] = '80a25e03dce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_boarding_points',
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('map_url', sa.String(), nullable=True),
    sa.Column('departure_time', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_package_boarding_points_package_id_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_boarding_points'))
    )
    op.create_index(op.f('ix_package_boarding_points_deleted_at'), 'package_boarding_points', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_package_boarding_points_id'), 'package_boarding_points', ['id'], unique=False)
    op.create_index(op.f('ix_package_boarding_points_package_id'), 'package_boarding_points', ['package_id'], unique=False)
    op.create_table('package_exclusions',
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_package_exclusions_package_id_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_exclusions'))
    )
    op.create_index(op.f('ix_package_exclusions_deleted_at'), 'package_exclusions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_package_exclusions_id'), 'package_exclusions', ['id'], unique=False)
    op.create_index(op.f('ix_package_exclusions_package_id'), 'package_exclusions', ['package_id'], unique=False)
    op.create_table('package_faqs',
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_package_faqs_package_id_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_faqs'))
    )
    op.create_index(op.f('ix_package_faqs_deleted_at'), 'package_faqs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_package_faqs_id'), 'package_faqs', ['id'], unique=False)
    op.create_index(op.f('ix_package_faqs_package_id'), 'package_faqs', ['package_id'], unique=False)
    op.create_table('package_gallery_images',
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('is_cover', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_package_gallery_images_package_id_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_gallery_images'))
    )
    op.create_index(op.f('ix_package_gallery_images_deleted_at'), 'package_gallery_images', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_package_gallery_images_id'), 'package_gallery_images', ['id'], unique=False)
    op.create_index(op.f('ix_package_gallery_images_package_id'), 'package_gallery_images', ['package_id'], unique=False)
    op.create_table('package_highlights',
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_package_highlights_package_id_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_highlights'))
    )
    op.create_index(op.f('ix_package_highlights_deleted_at'), 'package_highlights', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_package_highlights_id'), 'package_highlights', ['id'], unique=False)
    op.create_index(op.f('ix_package_highlights_package_id'), 'package_highlights', ['package_id'], unique=False)
    op.create_table('package_inclusions',
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_package_inclusions_package_id_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_inclusions'))
    )
    op.create_index(op.f('ix_package_inclusions_deleted_at'), 'package_inclusions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_package_inclusions_id'), 'package_inclusions', ['id'], unique=False)
    op.create_index(op.f('ix_package_inclusions_package_id'), 'package_inclusions', ['package_id'], unique=False)
    op.create_table('package_itinerary_days',
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_package_itinerary_days_package_id_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_itinerary_days'))
    )
    op.create_index(op.f('ix_package_itinerary_days_deleted_at'), 'package_itinerary_days', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_package_itinerary_days_id'), 'package_itinerary_days', ['id'], unique=False)
    op.create_index(op.f('ix_package_itinerary_days_package_id'), 'package_itinerary_days', ['package_id'], unique=False)
    op.create_table('package_policies',
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('CANCELLATION', 'CHECK_IN_OUT', 'TRAVEL_RULES', 'GENERAL', name='policytype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_package_policies_package_id_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_policies'))
    )
    op.create_index(op.f('ix_package_policies_deleted_at'), 'package_policies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_package_policies_id'), 'package_policies', ['id'], unique=False)
    op.create_index(op.f('ix_package_policies_package_id'), 'package_policies', ['package_id'], unique=False)
    op.create_index(op.f('ix_package_policies_type'), 'package_policies', ['type'], unique=False)
    op.create_table('room_faqs',
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_faqs_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_faqs'))
    )
    op.create_index(op.f('ix_room_faqs_deleted_at'), 'room_faqs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_room_faqs_id'), 'room_faqs', ['id'], unique=False)
    op.create_index(op.f('ix_room_faqs_room_id'), 'room_faqs', ['room_id'], unique=False)
    op.create_table('room_gallery_images',
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('is_cover', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_gallery_images_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_gallery_images'))
    )
    op.create_index(op.f('ix_room_gallery_images_deleted_at'), 'room_gallery_images', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_room_gallery_images_id'), 'room_gallery_images', ['id'], unique=False)
    op.create_index(op.f('ix_room_gallery_images_room_id'), 'room_gallery_images', ['room_id'], unique=False)
    op.create_table('room_highlights',
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_highlights_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_highlights'))
    )
    op.create_index(op.f('ix_room_highlights_deleted_at'), 'room_highlights', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_room_highlights_id'), 'room_highlights', ['id'], unique=False)
    op.create_index(op.f('ix_room_highlights_room_id'), 'room_highlights', ['room_id'], unique=False)
    op.create_table('room_policies',
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('CANCELLATION', 'CHECK_IN_OUT', 'TRAVEL_RULES', 'GENERAL', name='policytype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_policies_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_policies'))
    )
    op.create_index(op.f('ix_room_policies_deleted_at'), 'room_policies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_room_policies_id'), 'room_policies', ['id'], unique=False)
    op.create_index(op.f('ix_room_policies_room_id'), 'room_policies', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_policies_type'), 'room_policies', ['type'], unique=False)
    op.execute("ALTER TABLE packages ADD COLUMN IF NOT EXISTS meta_title VARCHAR")
    op.execute("ALTER TABLE packages ADD COLUMN IF NOT EXISTS meta_description VARCHAR")
    op.execute("ALTER TABLE packages ADD COLUMN IF NOT EXISTS og_image_url VARCHAR")
    op.execute("ALTER TABLE packages ADD COLUMN IF NOT EXISTS canonical_url VARCHAR")
    op.execute("ALTER TABLE rooms ADD COLUMN IF NOT EXISTS slug VARCHAR")
    
    # Data migration for existing rooms
    op.execute("UPDATE rooms SET slug = LOWER(REPLACE(lodge_name, ' ', '-')) || '-' || id WHERE slug IS NULL")
    
    op.alter_column('rooms', 'slug', nullable=False)
    op.execute("ALTER TABLE rooms ADD COLUMN IF NOT EXISTS meta_title VARCHAR")
    op.execute("ALTER TABLE rooms ADD COLUMN IF NOT EXISTS meta_description VARCHAR")
    op.execute("ALTER TABLE rooms ADD COLUMN IF NOT EXISTS og_image_url VARCHAR")
    op.execute("ALTER TABLE rooms ADD COLUMN IF NOT EXISTS canonical_url VARCHAR")
    op.create_index(op.f('ix_rooms_slug'), 'rooms', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_slug'), table_name='rooms')
    op.drop_column('rooms', 'canonical_url')
    op.drop_column('rooms', 'og_image_url')
    op.drop_column('rooms', 'meta_description')
    op.drop_column('rooms', 'meta_title')
    op.drop_column('rooms', 'slug')
    op.drop_column('packages', 'canonical_url')
    op.drop_column('packages', 'og_image_url')
    op.drop_column('packages', 'meta_description')
    op.drop_column('packages', 'meta_title')
    op.drop_index(op.f('ix_room_policies_type'), table_name='room_policies')
    op.drop_index(op.f('ix_room_policies_room_id'), table_name='room_policies')
    op.drop_index(op.f('ix_room_policies_id'), table_name='room_policies')
    op.drop_index(op.f('ix_room_policies_deleted_at'), table_name='room_policies')
    op.drop_table('room_policies')
    op.drop_index(op.f('ix_room_highlights_room_id'), table_name='room_highlights')
    op.drop_index(op.f('ix_room_highlights_id'), table_name='room_highlights')
    op.drop_index(op.f('ix_room_highlights_deleted_at'), table_name='room_highlights')
    op.drop_table('room_highlights')
    op.drop_index(op.f('ix_room_gallery_images_room_id'), table_name='room_gallery_images')
    op.drop_index(op.f('ix_room_gallery_images_id'), table_name='room_gallery_images')
    op.drop_index(op.f('ix_room_gallery_images_deleted_at'), table_name='room_gallery_images')
    op.drop_table('room_gallery_images')
    op.drop_index(op.f('ix_room_faqs_room_id'), table_name='room_faqs')
    op.drop_index(op.f('ix_room_faqs_id'), table_name='room_faqs')
    op.drop_index(op.f('ix_room_faqs_deleted_at'), table_name='room_faqs')
    op.drop_table('room_faqs')
    op.drop_index(op.f('ix_package_policies_type'), table_name='package_policies')
    op.drop_index(op.f('ix_package_policies_package_id'), table_name='package_policies')
    op.drop_index(op.f('ix_package_policies_id'), table_name='package_policies')
    op.drop_index(op.f('ix_package_policies_deleted_at'), table_name='package_policies')
    op.drop_table('package_policies')
    op.drop_index(op.f('ix_package_itinerary_days_package_id'), table_name='package_itinerary_days')
    op.drop_index(op.f('ix_package_itinerary_days_id'), table_name='package_itinerary_days')
    op.drop_index(op.f('ix_package_itinerary_days_deleted_at'), table_name='package_itinerary_days')
    op.drop_table('package_itinerary_days')
    op.drop_index(op.f('ix_package_inclusions_package_id'), table_name='package_inclusions')
    op.drop_index(op.f('ix_package_inclusions_id'), table_name='package_inclusions')
    op.drop_index(op.f('ix_package_inclusions_deleted_at'), table_name='package_inclusions')
    op.drop_table('package_inclusions')
    op.drop_index(op.f('ix_package_highlights_package_id'), table_name='package_highlights')
    op.drop_index(op.f('ix_package_highlights_id'), table_name='package_highlights')
    op.drop_index(op.f('ix_package_highlights_deleted_at'), table_name='package_highlights')
    op.drop_table('package_highlights')
    op.drop_index(op.f('ix_package_gallery_images_package_id'), table_name='package_gallery_images')
    op.drop_index(op.f('ix_package_gallery_images_id'), table_name='package_gallery_images')
    op.drop_index(op.f('ix_package_gallery_images_deleted_at'), table_name='package_gallery_images')
    op.drop_table('package_gallery_images')
    op.drop_index(op.f('ix_package_faqs_package_id'), table_name='package_faqs')
    op.drop_index(op.f('ix_package_faqs_id'), table_name='package_faqs')
    op.drop_index(op.f('ix_package_faqs_deleted_at'), table_name='package_faqs')
    op.drop_table('package_faqs')
    op.drop_index(op.f('ix_package_exclusions_package_id'), table_name='package_exclusions')
    op.drop_index(op.f('ix_package_exclusions_id'), table_name='package_exclusions')
    op.drop_index(op.f('ix_package_exclusions_deleted_at'), table_name='package_exclusions')
    op.drop_table('package_exclusions')
    op.drop_index(op.f('ix_package_boarding_points_package_id'), table_name='package_boarding_points')
    op.drop_index(op.f('ix_package_boarding_points_id'), table_name='package_boarding_points')
    op.drop_index(op.f('ix_package_boarding_points_deleted_at'), table_name='package_boarding_points')
    op.drop_table('package_boarding_points')
    # ### end Alembic commands ###
