"""add student package support

Revision ID: f8c15b05697f
Revises: a19ada80c104
Create Date: 2026-06-12 00:39:49.832865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c15b05697f'
down_revision: Union[str, Sequence[str], None] = 'a19ada80c104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_drafts_razorpay_order_id'), table_name='booking_drafts')
    op.create_index(op.f('ix_booking_drafts_pg_transaction_id'), 'booking_drafts', ['pg_transaction_id'], unique=True)
    op.add_column('booking_passengers', sa.Column('student_class', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('student_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('package_transport_options', sa.Column('student_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('package_transport_options', sa.Column('weekend_student_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('package_variants', sa.Column('student_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('package_variants', sa.Column('weekend_student_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('packages', sa.Column('is_student_package', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('packages', sa.Column('refreshment_student_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.create_index(op.f('ix_payments_pg_order_id'), 'payments', ['pg_order_id'], unique=True)
    op.create_index(op.f('ix_payments_pg_payment_id'), 'payments', ['pg_payment_id'], unique=True)
    op.add_column('system_settings', sa.Column('cashfree_app_id', sa.String(), nullable=True))
    op.drop_column('system_settings', 'razorpay_key_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('razorpay_key_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('system_settings', 'cashfree_app_id')
    op.drop_index(op.f('ix_payments_pg_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_pg_order_id'), table_name='payments')
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['pg_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['pg_order_id'], unique=True)
    op.drop_column('packages', 'refreshment_student_price')
    op.drop_column('packages', 'is_student_package')
    op.drop_column('package_variants', 'weekend_student_price')
    op.drop_column('package_variants', 'student_price')
    op.drop_column('package_transport_options', 'weekend_student_price')
    op.drop_column('package_transport_options', 'student_price')
    op.drop_column('bookings', 'student_count')
    op.drop_column('booking_passengers', 'student_class')
    op.drop_index(op.f('ix_booking_drafts_pg_transaction_id'), table_name='booking_drafts')
    op.create_index(op.f('ix_booking_drafts_razorpay_order_id'), 'booking_drafts', ['pg_transaction_id'], unique=True)
    # ### end Alembic commands ###
