"""add student package support

Revision ID: f8c15b05697f
Revises: a19ada80c104
Create Date: 2026-06-12 00:39:49.832865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c15b05697f'
down_revision: Union[str, Sequence[str], None] = 'a19ada80c104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_drafts_razorpay_order_id'), table_name='booking_drafts')
    op.create_index(op.f('ix_booking_drafts_pg_transaction_id'), 'booking_drafts', ['pg_transaction_id'], unique=True)
    op.execute("ALTER TABLE booking_passengers ADD COLUMN IF NOT EXISTS student_class VARCHAR(length=100)")
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS student_count INTEGER DEFAULT 0 NOT NULL")
    op.execute("ALTER TABLE package_transport_options ADD COLUMN IF NOT EXISTS student_price NUMERIC(10, 2)")
    op.execute("ALTER TABLE package_transport_options ADD COLUMN IF NOT EXISTS weekend_student_price NUMERIC(10, 2)")
    op.execute("ALTER TABLE package_variants ADD COLUMN IF NOT EXISTS student_price NUMERIC(10, 2)")
    op.execute("ALTER TABLE package_variants ADD COLUMN IF NOT EXISTS weekend_student_price NUMERIC(10, 2)")
    op.execute("ALTER TABLE packages ADD COLUMN IF NOT EXISTS is_student_package BOOLEAN DEFAULT 'false' NOT NULL")
    op.execute("ALTER TABLE packages ADD COLUMN IF NOT EXISTS refreshment_student_price NUMERIC(10, 2)")
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.create_index(op.f('ix_payments_pg_order_id'), 'payments', ['pg_order_id'], unique=True)
    op.create_index(op.f('ix_payments_pg_payment_id'), 'payments', ['pg_payment_id'], unique=True)
    op.execute("ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS cashfree_app_id VARCHAR")
    op.drop_column('system_settings', 'razorpay_key_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS razorpay_key_id VARCHAR")
    op.drop_column('system_settings', 'cashfree_app_id')
    op.drop_index(op.f('ix_payments_pg_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_pg_order_id'), table_name='payments')
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['pg_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['pg_order_id'], unique=True)
    op.drop_column('packages', 'refreshment_student_price')
    op.drop_column('packages', 'is_student_package')
    op.drop_column('package_variants', 'weekend_student_price')
    op.drop_column('package_variants', 'student_price')
    op.drop_column('package_transport_options', 'weekend_student_price')
    op.drop_column('package_transport_options', 'student_price')
    op.drop_column('bookings', 'student_count')
    op.drop_column('booking_passengers', 'student_class')
    op.drop_index(op.f('ix_booking_drafts_pg_transaction_id'), table_name='booking_drafts')
    op.create_index(op.f('ix_booking_drafts_razorpay_order_id'), 'booking_drafts', ['pg_transaction_id'], unique=True)
    # ### end Alembic commands ###
