"""Add EmailLog model

Revision ID: f9d65f0ca8a6
Revises: c1770dedc362
Create Date: 2026-05-22 21:58:40.797545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d65f0ca8a6'
down_revision: Union[str, Sequence[str], None] = 'c1770dedc362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=True),
    sa.Column('email_type', sa.String(), nullable=False),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_email_logs_booking_id_bookings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_logs'))
    )
    op.create_index(op.f('ix_email_logs_booking_id'), 'email_logs', ['booking_id'], unique=False)
    op.create_index(op.f('ix_email_logs_deleted_at'), 'email_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_packages_fts'), table_name='packages', postgresql_using='gin')
    op.create_index('ix_packages_fts', 'packages', [sa.literal_column("to_tsvector('english'::regconfig, title || ' ' || coalesce(description, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_packages_fts', table_name='packages', postgresql_using='gin')
    op.create_index(op.f('ix_packages_fts'), 'packages', [sa.literal_column("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_deleted_at'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_booking_id'), table_name='email_logs')
    op.drop_table('email_logs')
    # ### end Alembic commands ###
